openapi: 3.1.1
info:
  title: DATAtourisme Webservice
  version: "1.0"
  description: >
    Accès au flux touristique personnalisé généré via DATAtourisme.
    Ce webservice retourne des données au format JSON.

servers:
  - url: https://diffuseur.datatourisme.fr/webservice/8d1c63acc23712d759aa211bed76b442

paths:
  /{apiKey}:
    get:
      operationId: getTourismFlux
      summary: Récupérer les données du flux DATAtourisme
      parameters:
        - in: path
          name: apiKey
          required: true
          schema:
            type: string
          description: Clé API fournie par DATAtourisme (via Applications)
      responses:
        '200':
          description: Réponse JSON du flux
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        address:
                          type: string
                        type:
                          type: string

components: {}
