openapi: 3.0.0
info:
  title: DATAtourisme API
  version: "1.0"
servers:
  - url: https://diffuseur.datatourisme.fr/webservice/8d1c63acc23712d759aa211bed76b442/  # remplacez par l’URL de votre webservice
paths:
  /webservice:
    get:
      summary: Récupérer un flux de données touristiques
      parameters:
        - in: query
          name: apiKey
          schema:
            type: string
          required: true
          description: Clé API fournie par DATAtourisme
      responses:
        '200':
          description: Données du flux
          content:
            application/json:
              schema:
                type: object
