paths:
  /webservice:
    get:
      operationId: getFluxData  # nom unique pour cette opération
      summary: Récupérer un flux de données touristiques
      parameters:
        - in: query
          name: apiKey
          schema:
            type: string
          required: true
          description: Clé API fournie par DATAtourisme
      responses:
        '200':
          description: Données du flux
          content:
            application/json:
              schema:
                type: object
